"""temp

Revision ID: 366834372fb2
Revises: d57c3ca1d6cc
Create Date: 2020-07-31 16:27:59.818500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366834372fb2'
down_revision = 'd57c3ca1d6cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_couple', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_couple')
    # ### end Alembic commands ###
