"""0802_unique

Revision ID: 69ac4343dd8f
Revises: 36843f6defb8
Create Date: 2020-08-02 15:36:12.554333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ac4343dd8f'
down_revision = '36843f6defb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_question_unique', 'user_answers', ['user_id', 'question_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_question_unique', 'user_answers', type_='unique')
    # ### end Alembic commands ###
