"""sms_auth

Revision ID: d57c3ca1d6cc
Revises: 051f77a0cb28
Create Date: 2020-07-30 18:56:14.815432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd57c3ca1d6cc'
down_revision = '051f77a0cb28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_key', mysql.CHAR(length=80), nullable=True),
    sa.Column('auth_value', mysql.CHAR(length=10), nullable=True),
    sa.Column('phone_num', mysql.CHAR(length=20), nullable=True),
    sa.Column('expiration', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user_sessions', 'third_party_token')
    op.drop_column('user_sessions', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user_sessions', sa.Column('third_party_token', mysql.TEXT(), nullable=True))
    op.drop_table('sms_auth')
    # ### end Alembic commands ###
