openapi: 3.0.0

info:
  version: '1.0'
  title: '2ulip clone coding'
  description: '어플리케이션 튤립의 API 서버를 상상하며 따라해 봅니다.'

paths:
  /:
    $ref: 'rest/health.yaml#/hi'

  # Users
  /users/signup:
    $ref: 'rest/user.yaml#/signup'
  /users/login:
    $ref: 'rest/user.yaml#/login'
  /users/me:
    $ref: 'rest/user.yaml#/me'

  # Sms
  /sms:
    $ref: 'rest/sms.yaml#/sms'

  # Questions & Answers
  /question/match:
    $ref: 'rest/question.yaml#/match_question'
  /question/answered:
    $ref: 'rest/question.yaml#/answered_question'
  /question/unanswered:
    $ref: 'rest/question.yaml#/unanswered_question'
  /answers:
    $ref: 'rest/question.yaml#/answer'


components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      x-bearerInfoFunc: libs.route.login_required.login_required
